aliases:
  # commands
  - &yarn
    name: Install Dependencies
    command: |
      yarn install
  - &test
    name: Run Tests
    command: |
      yarn test

defaults: &defaults
  environment:
    CIRCLE: true
  working_directory: ~/project
  docker:
    - image: circleci/node:lts

version: 2.1

jobs:
  install_lint_test:
    <<: *defaults
    steps:
      - checkout
      - run: *yarn
      - run: *test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_lint_test

# version: 2
# jobs:
#   build:    
#     docker:
#       - image: cirrusci/flutter:v1.5.8 

#     branches:
#       only: master

#     steps:
#       - checkout

#       - run:
#           name: Run Flutter doctor
#           command: flutter doctor

#       - run:
#           name: Run the application tests
#           command: flutter test

#       - run:
#           name: Build the Android version
#           command: flutter build apk 

#       - store_artifacts:
#           path: build/app/outputs/apk/release/app-release.apk
